environment:
  matrix:
    - CMAKE_GENERATOR: "Visual Studio 14 2015"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_GENERATOR: "Visual Studio 15 2017"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      CMAKE_GENERATOR: "Visual Studio 16 2019"

artifacts:
  - path: build
    name: build

build_script:
  - cmd: git submodule update --init --recursive
  - cmd: python scripts/lint.py
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake -G "%CMAKE_GENERATOR%" .. -A Win32
  - cmd: cmake --build .
  - cmd: cd ..
  - cmd: scripts/run.bat